// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqNFMFxRM3cNXHiKfWH_68AZbn-ZuK3w',
    appId: '1:997387779603:android:b17408871a2faae574c9e6',
    messagingSenderId: '997387779603',
    projectId: 'hiob-6dd5e',
    storageBucket: 'hiob-6dd5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPAmlv2hnsJR6ruEFbyOP2b98SxJ1mfbE',
    appId: '1:997387779603:ios:441fbb0497c86c5d74c9e6',
    messagingSenderId: '997387779603',
    projectId: 'hiob-6dd5e',
    storageBucket: 'hiob-6dd5e.firebasestorage.app',
    iosBundleId: 'de.bachmaier.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjiLV8pjgd8kLwEF_19bjgaT-FnVIkM4w',
    appId: '1:997387779603:web:cf13e6765992f28774c9e6',
    messagingSenderId: '997387779603',
    projectId: 'hiob-6dd5e',
    authDomain: 'hiob-6dd5e.firebaseapp.com',
    storageBucket: 'hiob-6dd5e.firebasestorage.app',
  );

}