// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Jiw8hwO9oUliEHHgdWVcWmhyg8UA3tI',
    appId: '1:951761708298:android:e5083a69c44dac68b1c6f3',
    messagingSenderId: '951761708298',
    projectId: 'hiob-60f81',
    storageBucket: 'hiob-60f81.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQmlBvhwS4m49Q3H4_R4FlIQpudpiLEI',
    appId: '1:951761708298:ios:7baf5a2193698a98b1c6f3',
    messagingSenderId: '951761708298',
    projectId: 'hiob-60f81',
    storageBucket: 'hiob-60f81.firebasestorage.app',
    iosBundleId: 'de.bachmaier.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACxeN9X8h3AA0icvziq0S81D2zbnl23As',
    appId: '1:951761708298:web:1318596a0994b3eab1c6f3',
    messagingSenderId: '951761708298',
    projectId: 'hiob-60f81',
    authDomain: 'hiob-60f81.firebaseapp.com',
    storageBucket: 'hiob-60f81.firebasestorage.app',
  );
}
