import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:ionicons/ionicons.dart';

Map<String, IconData> icons = {
  "import export": Icons.import_export,
  "home": Icons.home,
  "home outlined": Icons.home_outlined,
  "home work": Icons.home_work,
  "light bulb": Icons.lightbulb,
  "light": Icons.light,
  "light outlined": Icons.light_outlined,
  "highlight rounded": Icons.highlight_rounded,
  "window": Icons.window,
  "window sharp": Icons.window_sharp,
  "stream": Icons.stream,
  "living": Icons.living,
  "living outlined": Icons.living_outlined,
  "family restroom": Icons.family_restroom,
  "checkroom outlined": Icons.checkroom_outlined,
  "bathroom": Icons.bathroom,
  "ac unit": Icons.ac_unit,
  "ac unit rounded": Icons.ac_unit_rounded,
  "access alarm": Icons.alarm,
  "access time outlines": Icons.access_time_outlined,
  "accessibility": Icons.accessibility,
  "account box": Icons.account_box,
  "account tree": Icons.account_tree,
  "adb": Icons.adb,
  "directions car": Icons.directions_car,
  "electric car": Icons.electric_car,
  "electric car outlined": Icons.electric_car_outlined,
  "adf scanner": Icons.adf_scanner,
  "ad scanner outlined": Icons.adf_scanner_outlined,
  "air": Icons.air,
  "airline seat recline normal rounded":
      Icons.airline_seat_recline_normal_rounded,
  "all inbox": Icons.all_inbox,
  "analytics outlined": Icons.analytics_outlined,
  "analytics": Icons.analytics,
  "android": Icons.android,
  "aod handy": Icons.aod,
  "apartment": Icons.apartment,
  "assessment": Icons.assessment,
  "attachment": Icons.attachment,
  "attractions": Icons.attractions,
  "audiotrack": Icons.audiotrack,
  "bathtub": Icons.bathtub,
  "bathtub outlined": Icons.bathtub_outlined,
  "battery alert": Icons.battery_alert,
  "battery charging full": Icons.battery_charging_full,
  "battery full": Icons.battery_full,
  "bed": Icons.bed,
  "bedroom child outlined": Icons.bedroom_child_outlined,
  "bedroom child": Icons.bedroom_child,
  "bedroom parent": Icons.bedroom_parent,
  "bedroom parent outlined": Icons.bedroom_parent_outlined,
  "moon": Icons.bedtime,
  "blender mixer": Icons.blender,
  "bolt": Icons.bolt,
  "boy": Icons.boy,
  "brunch dining": Icons.brunch_dining,
  "bungalow": Icons.bungalow,
  "business": Icons.business,
  "calendar month": Icons.calendar_month,
  "calendar month outlined": Icons.calendar_month_outlined,
  "call": Icons.call,
  "camera alt": Icons.camera_alt,
  "cast outlined": Icons.cast_outlined,
  "chair outlined": Icons.chair_outlined,
  "chair": Icons.chair,
  "coffee": Icons.coffee,
  "coffee maker": Icons.coffee_maker,
  "coffee maker outlined": Icons.coffee_maker_outlined,
  "delete": Icons.delete,
  "delete outlined": Icons.delete_outline,
  "desktop mac": Icons.desktop_mac,
  "device thermostat": Icons.device_thermostat,
  "devices": Icons.devices,
  "directions car filled outlined": Icons.directions_car_filled_outlined,
  "door back door": Icons.door_back_door,
  "door back door outlined": Icons.door_back_door_outlined,
  "doorbell": Icons.doorbell,
  "doorbell outlined": Icons.doorbell_outlined,
  "drafts mail post": Icons.drafts,
  "drafts mail post outlined": Icons.drafts_outlined,
  "electrical services": Icons.electric_car_outlined,
  "email": Icons.email,
  "email outlined": Icons.email_outlined,
  "fireplace": Icons.fireplace,
  "flashlight on": Icons.flashlight_on,
  "garage": Icons.garage,
  "garage outlined": Icons.garage_outlined,
  "group": Icons.group,
  "headphones": Icons.headphones,
  "hot tub": Icons.hot_tub,
  "house": Icons.house,
  "house outlined": Icons.house_outlined,
  "print": Icons.print,
  "print outlined": Icons.print_outlined,
  "print disabled": Icons.print_disabled,
  "microwave": Icons.microwave,
  "microwave outlined": Icons.microwave_outlined,
  "water": Icons.water,
  "water damage": Icons.water_damage,
  "water damage outline": Icons.water_damage_outlined,
  "sensor": Icons.sensors,
  "sensor off": Icons.sensors_off,
  "bell": FontAwesomeIcons.bell,
  "kitchen": FontAwesomeIcons.kitchenSet,
  "fire Burner": FontAwesomeIcons.fireBurner,
  "remove": Ionicons.remove,
  "attach sharp": Ionicons.attach_sharp,
  "planet outline": Ionicons.planet_outline,
  "trophy outline": Ionicons.trophy_outline,
  "arrow forward circle outline": Ionicons.arrow_forward_circle_outline,
  "locate sharp": Ionicons.locate_sharp,
  "volume off outline": Ionicons.volume_off_outline,
  "attach outline": Ionicons.attach_outline,
  "swap horizontal sharp": Ionicons.swap_horizontal_sharp,
  "flash sharp": Ionicons.flash_sharp,
  "volume high outline": Ionicons.volume_high_outline,
  "arrow undo sharp": Ionicons.arrow_undo_sharp,
  "checkmark circle outline": Ionicons.checkmark_circle_outline,
  "reorder two": Ionicons.reorder_two,
  "mic off circle": Ionicons.mic_off_circle,
  "logo github": Ionicons.logo_github,
  "pie chart sharp": Ionicons.pie_chart_sharp,
  "stopwatch": Ionicons.stopwatch,
  "add": Ionicons.add,
  "key sharp": Ionicons.key_sharp,
  "language sharp": Ionicons.language_sharp,
  "grid outline": Ionicons.grid_outline,
  "partly sunny sharp": Ionicons.partly_sunny_sharp,
  "push sharp": Ionicons.push_sharp,
  "logo bitcoin": Ionicons.logo_bitcoin,
  "medal": Ionicons.medal,
  "bus outline": Ionicons.bus_outline,
  "mail open": Ionicons.mail_open,
  "warning sharp": Ionicons.warning_sharp,
  "mic circle": Ionicons.mic_circle,
  "at circle": Ionicons.at_circle,
  "battery charging outline": Ionicons.battery_charging_outline,
  "refresh circle sharp": Ionicons.refresh_circle_sharp,
  "scan circle outline": Ionicons.scan_circle_outline,
  "rocket sharp": Ionicons.rocket_sharp,
  "flash off sharp": Ionicons.flash_off_sharp,
  "flag sharp": Ionicons.flag_sharp,
  "chatbox ellipses": Ionicons.chatbox_ellipses,
  "arrow forward circle": Ionicons.arrow_forward_circle,
  "stats chart": Ionicons.stats_chart,
  "laptop": Ionicons.laptop,
  "toggle sharp": Ionicons.toggle_sharp,
  "scale outline": Ionicons.scale_outline,
  "reorder four sharp": Ionicons.reorder_four_sharp,
  "hammer": Ionicons.hammer,
  "volume medium outline": Ionicons.volume_medium_outline,
  "podium": Ionicons.podium,
  "mic outline": Ionicons.mic_outline,
  "chatbox ellipses sharp": Ionicons.chatbox_ellipses_sharp,
  "star sharp": Ionicons.star_sharp,
  "move outline": Ionicons.move_outline,
  "golf outline": Ionicons.golf_outline,
  "person remove outline": Ionicons.person_remove_outline,
  "caret down circle sharp": Ionicons.caret_down_circle_sharp,
  "play circle outline": Ionicons.play_circle_outline,
  "save sharp": Ionicons.save_sharp,
  "newspaper": Ionicons.newspaper,
  "wifi outline": Ionicons.wifi_outline,
  "fish outline": Ionicons.fish_outline,
  "logo discord": Ionicons.logo_discord,
  "reorder two sharp": Ionicons.reorder_two_sharp,
  "bug": Ionicons.bug,
  "logo designernews": Ionicons.logo_designernews,
  "sad": Ionicons.sad,
  "camera outline": Ionicons.camera_outline,
  "football sharp": Ionicons.football_sharp,
  "play forward circle": Ionicons.play_forward_circle,
  "pricetags sharp": Ionicons.pricetags_sharp,
  "heart circle sharp": Ionicons.heart_circle_sharp,
  "cloud offline sharp": Ionicons.cloud_offline_sharp,
  "woman": Ionicons.woman,
  "chevron up circle outline": Ionicons.chevron_up_circle_outline,
  "bag add outline": Ionicons.bag_add_outline,
  "lock closed": Ionicons.lock_closed,
  "battery half sharp": Ionicons.battery_half_sharp,
  "mic off circle outline": Ionicons.mic_off_circle_outline,
  "search circle": Ionicons.search_circle,
  "nuclear outline": Ionicons.nuclear_outline,
  "document text outline": Ionicons.document_text_outline,
  "file tray stacked sharp": Ionicons.file_tray_stacked_sharp,
  "reload outline": Ionicons.reload_outline,
  "school outline": Ionicons.school_outline,
  "checkmark done circle sharp": Ionicons.checkmark_done_circle_sharp,
  "people circle outline": Ionicons.people_circle_outline,
  "hand left": Ionicons.hand_left,
  "thermometer": Ionicons.thermometer,
  "logo medium": Ionicons.logo_medium,
  "reload": Ionicons.reload,
  "reorder three outline": Ionicons.reorder_three_outline,
  "language": Ionicons.language,
  "bag handle outline": Ionicons.bag_handle_outline,
  "color wand sharp": Ionicons.color_wand_sharp,
  "trophy": Ionicons.trophy,
  "stop circle sharp": Ionicons.stop_circle_sharp,
  "fish": Ionicons.fish,
  "bag handle sharp": Ionicons.bag_handle_sharp,
  "prism sharp": Ionicons.prism_sharp,
  "notifications off outline": Ionicons.notifications_off_outline,
  "Ionicons accessibility": Ionicons.accessibility,
  "apps outline": Ionicons.apps_outline,
  "attach": Ionicons.attach,
  "link outline": Ionicons.link_outline,
  "transgender sharp": Ionicons.transgender_sharp,
  "megaphone outline": Ionicons.megaphone_outline,
  "people outline": Ionicons.people_outline,
  "hand right": Ionicons.hand_right,
  "arrow undo circle outline": Ionicons.arrow_undo_circle_outline,
  "musical note": Ionicons.musical_note,
  "train outline": Ionicons.train_outline,
  "at outline": Ionicons.at_outline,
  "file tray": Ionicons.file_tray,
  "cog sharp": Ionicons.cog_sharp,
  "sync outline": Ionicons.sync_outline,
  "scale sharp": Ionicons.scale_sharp,
  "dice outline": Ionicons.dice_outline,
  "scan circle": Ionicons.scan_circle,
  "fitness outline": Ionicons.fitness_outline,
  "arrow down circle sharp": Ionicons.arrow_down_circle_sharp,
  "pricetags": Ionicons.pricetags,
  "ellipse sharp": Ionicons.ellipse_sharp,
  "radio": Ionicons.radio,
  "pencil outline": Ionicons.pencil_outline,
  "bookmark sharp": Ionicons.bookmark_sharp,
  "push": Ionicons.push,
  "arrow up circle sharp": Ionicons.arrow_up_circle_sharp,
  "checkmark sharp": Ionicons.checkmark_sharp,
  "rose": Ionicons.rose,
  "ellipsis vertical circle": Ionicons.ellipsis_vertical_circle,
  "shirt": Ionicons.shirt,
  "document attach": Ionicons.document_attach,
  "medkit sharp": Ionicons.medkit_sharp,
  "logo xing": Ionicons.logo_xing,
  "podium outline": Ionicons.podium_outline,
  "volume mute sharp": Ionicons.volume_mute_sharp,
  "cart outline": Ionicons.cart_outline,
  "link": Ionicons.link,
  "arrow redo": Ionicons.arrow_redo,
  "lock open": Ionicons.lock_open,
  "arrow redo outline": Ionicons.arrow_redo_outline,
  "tennisball sharp": Ionicons.tennisball_sharp,
  "chatbox outline": Ionicons.chatbox_outline,
  "thermometer outline": Ionicons.thermometer_outline,
  "notifications off circle sharp": Ionicons.notifications_off_circle_sharp,
  "arrow undo circle": Ionicons.arrow_undo_circle,
  "chevron down circle sharp": Ionicons.chevron_down_circle_sharp,
  "cloudy outline": Ionicons.cloudy_outline,
  "hourglass": Ionicons.hourglass,
  "return down forward": Ionicons.return_down_forward,
  "reader": Ionicons.reader,
  "id card": Ionicons.id_card,
  "volume mute": Ionicons.volume_mute,
  "list sharp": Ionicons.list_sharp,
  "bandage": Ionicons.bandage,
  "bar chart outline": Ionicons.bar_chart_outline,
  "qr code sharp": Ionicons.qr_code_sharp,
  "person circle sharp": Ionicons.person_circle_sharp,
  "baseball": Ionicons.baseball,
  "Ionicons home": Ionicons.home,
  "footsteps sharp": Ionicons.footsteps_sharp,
  "disc sharp": Ionicons.disc_sharp,
  "pricetag": Ionicons.pricetag,
  "arrow undo": Ionicons.arrow_undo,
  "logo yahoo": Ionicons.logo_yahoo,
  "logo usd": Ionicons.logo_usd,
  "arrow redo circle outline": Ionicons.arrow_redo_circle_outline,
  "medal outline": Ionicons.medal_outline,
  "play skip back": Ionicons.play_skip_back,
  "play skip forward": Ionicons.play_skip_forward,
  "swap horizontal": Ionicons.swap_horizontal,
  "settings sharp": Ionicons.settings_sharp,
  "mail unread outline": Ionicons.mail_unread_outline,
  "navigate": Ionicons.navigate,
  "prism outline": Ionicons.prism_outline,
  "globe outline": Ionicons.globe_outline,
  "rose outline": Ionicons.rose_outline,
  "document attach sharp": Ionicons.document_attach_sharp,
  "git commit sharp": Ionicons.git_commit_sharp,
  "caret up circle outline": Ionicons.caret_up_circle_outline,
  "logo wordpress": Ionicons.logo_wordpress,
  "checkmark done sharp": Ionicons.checkmark_done_sharp,
  "git branch outline": Ionicons.git_branch_outline,
  "restaurant outline": Ionicons.restaurant_outline,
  "pint": Ionicons.pint,
  "mail sharp": Ionicons.mail_sharp,
  "help buoy sharp": Ionicons.help_buoy_sharp,
  "return up back": Ionicons.return_up_back,
  "invert mode outline": Ionicons.invert_mode_outline,
  "ellipsis horizontal circle sharp": Ionicons.ellipsis_horizontal_circle_sharp,
  "bag remove": Ionicons.bag_remove,
  "airplane outline": Ionicons.airplane_outline,
  "battery half outline": Ionicons.battery_half_outline,
  "key": Ionicons.key,
  "create sharp": Ionicons.create_sharp,
  "repeat sharp": Ionicons.repeat_sharp,
  "search": Ionicons.search,
  "wallet sharp": Ionicons.wallet_sharp,
  "code working sharp": Ionicons.code_working_sharp,
  "caret back circle": Ionicons.caret_back_circle,
  "car sharp": Ionicons.car_sharp,
  "options outline": Ionicons.options_outline,
  "book sharp": Ionicons.book_sharp,
  "easel outline": Ionicons.easel_outline,
  "calculator": Ionicons.calculator,
  "trail sign outline": Ionicons.trail_sign_outline,
  "logo octocat": Ionicons.logo_octocat,
  "male": Ionicons.male,
  "subway outline": Ionicons.subway_outline,
  "sync": Ionicons.sync,
  "list circle outline": Ionicons.list_circle_outline,
  "flag": Ionicons.flag,
  "aperture": Ionicons.aperture,
  "toggle": Ionicons.toggle,
  "call outline": Ionicons.call_outline,
  "cloud upload sharp": Ionicons.cloud_upload_sharp,
  "mic circle sharp": Ionicons.mic_circle_sharp,
  "chevron up circle": Ionicons.chevron_up_circle,
  "chevron back circle": Ionicons.chevron_back_circle,
  "help circle": Ionicons.help_circle,
  "receipt outline": Ionicons.receipt_outline,
  "balloon sharp": Ionicons.balloon_sharp,
  "search circle outline": Ionicons.search_circle_outline,
  "return down back": Ionicons.return_down_back,
  "heart circle": Ionicons.heart_circle,
  "square sharp": Ionicons.square_sharp,
  "contract": Ionicons.contract,
  "reader outline": Ionicons.reader_outline,
  "cloud circle sharp": Ionicons.cloud_circle_sharp,
  "cellular": Ionicons.cellular,
  "at circle sharp": Ionicons.at_circle_sharp,
  "play back circle": Ionicons.play_back_circle,
  "beer": Ionicons.beer,
  "medical outline": Ionicons.medical_outline,
  "logo npm": Ionicons.logo_npm,
  "battery dead": Ionicons.battery_dead,
  "close circle sharp": Ionicons.close_circle_sharp,
  "logo no smoking": Ionicons.logo_no_smoking,
  "warning outline": Ionicons.warning_outline,
  "cloud offline": Ionicons.cloud_offline,
  "create outline": Ionicons.create_outline,
  "chatbubbles outline": Ionicons.chatbubbles_outline,
  "filter circle": Ionicons.filter_circle,
  "leaf sharp": Ionicons.leaf_sharp,
  "pulse outline": Ionicons.pulse_outline,
  "watch outline": Ionicons.watch_outline,
  "calendar clear sharp": Ionicons.calendar_clear_sharp,
  "tv sharp": Ionicons.tv_sharp,
  "return down back outline": Ionicons.return_down_back_outline,
  "enter sharp": Ionicons.enter_sharp,
  "fast food outline": Ionicons.fast_food_outline,
  "pie chart outline": Ionicons.pie_chart_outline,
  "ticket sharp": Ionicons.ticket_sharp,
  "git commit outline": Ionicons.git_commit_outline,
  "timer": Ionicons.timer,
  "terminal sharp": Ionicons.terminal_sharp,
  "git merge": Ionicons.git_merge,
  "git network sharp": Ionicons.git_network_sharp,
  "lock open sharp": Ionicons.lock_open_sharp,
  "glasses sharp": Ionicons.glasses_sharp,
  "id card outline": Ionicons.id_card_outline,
  "car sport outline": Ionicons.car_sport_outline,
  "caret forward circle": Ionicons.caret_forward_circle,
  "happy outline": Ionicons.happy_outline,
  "cloud done": Ionicons.cloud_done,
  "bar chart sharp": Ionicons.bar_chart_sharp,
  "logo windows": Ionicons.logo_windows,
  "hand left sharp": Ionicons.hand_left_sharp,
  "hammer sharp": Ionicons.hammer_sharp,
  "volume low": Ionicons.volume_low,
  "refresh circle": Ionicons.refresh_circle,
  "image": Ionicons.image,
  "person sharp": Ionicons.person_sharp,
  "briefcase": Ionicons.briefcase,
  "contrast": Ionicons.contrast,
  "easel sharp": Ionicons.easel_sharp,
  "file tray sharp": Ionicons.file_tray_sharp,
  "thumbs down sharp": Ionicons.thumbs_down_sharp,
  "checkmark done outline": Ionicons.checkmark_done_outline,
  "save": Ionicons.save,
  "layers": Ionicons.layers,
  "time": Ionicons.time,
  "train": Ionicons.train,
  "log out sharp": Ionicons.log_out_sharp,
  "square outline": Ionicons.square_outline,
  "mail unread": Ionicons.mail_unread,
  "reorder two outline": Ionicons.reorder_two_outline,
  "checkmark done": Ionicons.checkmark_done,
  "cafe sharp": Ionicons.cafe_sharp,
  "logo xbox": Ionicons.logo_xbox,
  "bag add": Ionicons.bag_add,
  "checkbox": Ionicons.checkbox,
  "unlink outline": Ionicons.unlink_outline,
  "chevron up outline": Ionicons.chevron_up_outline,
  "film sharp": Ionicons.film_sharp,
  "play skip forward circle outline": Ionicons.play_skip_forward_circle_outline,
  "git network outline": Ionicons.git_network_outline,
  "language outline": Ionicons.language_outline,
  "calendar outline": Ionicons.calendar_outline,
  "git network": Ionicons.git_network,
  "logo reddit": Ionicons.logo_reddit,
  "chevron forward circle sharp": Ionicons.chevron_forward_circle_sharp,
  "key outline": Ionicons.key_outline,
  "logo rss": Ionicons.logo_rss,
  "code slash": Ionicons.code_slash,
  "return up forward sharp": Ionicons.return_up_forward_sharp,
  "information circle sharp": Ionicons.information_circle_sharp,
  "notifications sharp": Ionicons.notifications_sharp,
  "code download": Ionicons.code_download,
  "toggle outline": Ionicons.toggle_outline,
  "shield half": Ionicons.shield_half,
  "leaf outline": Ionicons.leaf_outline,
  "storefront": Ionicons.storefront,
  "crop sharp": Ionicons.crop_sharp,
  "logo mastodon": Ionicons.logo_mastodon,
  "pulse": Ionicons.pulse,
  "mic off": Ionicons.mic_off,
  "pricetag outline": Ionicons.pricetag_outline,
  "hand right outline": Ionicons.hand_right_outline,
  "person add sharp": Ionicons.person_add_sharp,
  "flask": Ionicons.flask,
  "home outline": Ionicons.home_outline,
  "heart dislike sharp": Ionicons.heart_dislike_sharp,
  "bed sharp": Ionicons.bed_sharp,
  "ice cream sharp": Ionicons.ice_cream_sharp,
  "egg sharp": Ionicons.egg_sharp,
  "Ionicons analytics": Ionicons.analytics,
  "backspace": Ionicons.backspace,
  "close": Ionicons.close,
  "list outline": Ionicons.list_outline,
  "thumbs down": Ionicons.thumbs_down,
  "male female sharp": Ionicons.male_female_sharp,
  "send outline": Ionicons.send_outline,
  "hourglass outline": Ionicons.hourglass_outline,
  "logo dropbox": Ionicons.logo_dropbox,
  "pin sharp": Ionicons.pin_sharp,
  "chevron down circle": Ionicons.chevron_down_circle,
  "mic circle outline": Ionicons.mic_circle_outline,
  "contract sharp": Ionicons.contract_sharp,
  "accessibility sharp": Ionicons.accessibility_sharp,
  "settings": Ionicons.settings,
  "person circle": Ionicons.person_circle,
  "football": Ionicons.football,
  "trash": Ionicons.trash,
  "scan sharp": Ionicons.scan_sharp,
  "return down forward sharp": Ionicons.return_down_forward_sharp,
  "add sharp": Ionicons.add_sharp,
  "shapes sharp": Ionicons.shapes_sharp,
  "extension puzzle sharp": Ionicons.extension_puzzle_sharp,
  "megaphone sharp": Ionicons.megaphone_sharp,
  "arrow back circle": Ionicons.arrow_back_circle,
  "funnel sharp": Ionicons.funnel_sharp,
  "resize": Ionicons.resize,
  "search circle sharp": Ionicons.search_circle_sharp,
  "keypad": Ionicons.keypad,
  "chatbubble sharp": Ionicons.chatbubble_sharp,
  "logo soundcloud": Ionicons.logo_soundcloud,
  "fast food sharp": Ionicons.fast_food_sharp,
  "woman sharp": Ionicons.woman_sharp,
  "radio button on sharp": Ionicons.radio_button_on_sharp,
  "server": Ionicons.server,
  "caret back circle sharp": Ionicons.caret_back_circle_sharp,
  "document lock sharp": Ionicons.document_lock_sharp,
  "wine sharp": Ionicons.wine_sharp,
  "bug outline": Ionicons.bug_outline,
  "add outline": Ionicons.add_outline,
  "code working": Ionicons.code_working,
  "mail": Ionicons.mail,
  "battery charging": Ionicons.battery_charging,
  "log in": Ionicons.log_in,
  "boat outline": Ionicons.boat_outline,
  "cloudy sharp": Ionicons.cloudy_sharp,
  "search sharp": Ionicons.search_sharp,
  "videocam outline": Ionicons.videocam_outline,
  "ban": Ionicons.ban,
  "car sport sharp": Ionicons.car_sport_sharp,
  "locate": Ionicons.locate,
  "wifi": Ionicons.wifi,
  "play back": Ionicons.play_back,
  "calendar": Ionicons.calendar,
  "chevron back sharp": Ionicons.chevron_back_sharp,
  "documents outline": Ionicons.documents_outline,
  "logo wechat": Ionicons.logo_wechat,
  "construct sharp": Ionicons.construct_sharp,
  "arrow back outline": Ionicons.arrow_back_outline,
  "color wand outline": Ionicons.color_wand_outline,
  "arrow up circle outline": Ionicons.arrow_up_circle_outline,
  "pencil sharp": Ionicons.pencil_sharp,
  "expand sharp": Ionicons.expand_sharp,
  "storefront sharp": Ionicons.storefront_sharp,
  "ban sharp": Ionicons.ban_sharp,
  "ticket": Ionicons.ticket,
  "file tray stacked": Ionicons.file_tray_stacked,
  "brush": Ionicons.brush,
  "checkbox sharp": Ionicons.checkbox_sharp,
  "hand left outline": Ionicons.hand_left_outline,
  "globe sharp": Ionicons.globe_sharp,
  "at sharp": Ionicons.at_sharp,
  "calculator sharp": Ionicons.calculator_sharp,
  "logo capacitor": Ionicons.logo_capacitor,
  "wallet outline": Ionicons.wallet_outline,
  "sync circle sharp": Ionicons.sync_circle_sharp,
  "arrow down outline": Ionicons.arrow_down_outline,
  "ellipsis vertical": Ionicons.ellipsis_vertical,
  "flask outline": Ionicons.flask_outline,
  "return up back outline": Ionicons.return_up_back_outline,
  "shield": Ionicons.shield,
  "trending up": Ionicons.trending_up,
  "close sharp": Ionicons.close_sharp,
  "chevron up sharp": Ionicons.chevron_up_sharp,
  "basketball outline": Ionicons.basketball_outline,
  "wifi sharp": Ionicons.wifi_sharp,
  "radio outline": Ionicons.radio_outline,
  "sync sharp": Ionicons.sync_sharp,
  "recording": Ionicons.recording,
  "rainy outline": Ionicons.rainy_outline,
  "logo foursquare": Ionicons.logo_foursquare,
  "bonfire": Ionicons.bonfire,
  "laptop sharp": Ionicons.laptop_sharp,
  "ice cream": Ionicons.ice_cream,
  "bowling ball sharp": Ionicons.bowling_ball_sharp,
  "card outline": Ionicons.card_outline,
  "phone portrait": Ionicons.phone_portrait,
  "nutrition sharp": Ionicons.nutrition_sharp,
  "earth sharp": Ionicons.earth_sharp,
  "shapes": Ionicons.shapes,
  "umbrella": Ionicons.umbrella,
  "umbrella sharp": Ionicons.umbrella_sharp,
  "cloud download": Ionicons.cloud_download,
  "bicycle sharp": Ionicons.bicycle_sharp,
  "baseball sharp": Ionicons.baseball_sharp,
  "ribbon sharp": Ionicons.ribbon_sharp,
  "construct outline": Ionicons.construct_outline,
  "caret back": Ionicons.caret_back,
  "archive outline": Ionicons.archive_outline,
  "server outline": Ionicons.server_outline,
  "create": Ionicons.create,
  "trending down sharp": Ionicons.trending_down_sharp,
  "arrow down circle outline": Ionicons.arrow_down_circle_outline,
  "logo vue": Ionicons.logo_vue,
  "cube": Ionicons.cube,
  "volume mute outline": Ionicons.volume_mute_outline,
  "git commit": Ionicons.git_commit,
  "copy sharp": Ionicons.copy_sharp,
  "sparkles": Ionicons.sparkles,
  "share social sharp": Ionicons.share_social_sharp,
  "move": Ionicons.move,
  "desktop outline": Ionicons.desktop_outline,
  "reload sharp": Ionicons.reload_sharp,
  "gift": Ionicons.gift,
  "link sharp": Ionicons.link_sharp,
  "logo css3": Ionicons.logo_css3,
  "navigate circle outline": Ionicons.navigate_circle_outline,
  "briefcase outline": Ionicons.briefcase_outline,
  "camera": Ionicons.camera,
  "arrow back": Ionicons.arrow_back,
  "videocam sharp": Ionicons.videocam_sharp,
  "bluetooth outline": Ionicons.bluetooth_outline,
  "glasses": Ionicons.glasses,
  "logo tableau": Ionicons.logo_tableau,
  "fish sharp": Ionicons.fish_sharp,
  "refresh circle outline": Ionicons.refresh_circle_outline,
  "pizza sharp": Ionicons.pizza_sharp,
  "return up back sharp": Ionicons.return_up_back_sharp,
  "heart dislike": Ionicons.heart_dislike,
  "battery charging sharp": Ionicons.battery_charging_sharp,
  "logo whatsapp": Ionicons.logo_whatsapp,
  "play skip forward outline": Ionicons.play_skip_forward_outline,
  "send sharp": Ionicons.send_sharp,
  "browsers outline": Ionicons.browsers_outline,
  "videocam off": Ionicons.videocam_off,
  "calculator outline": Ionicons.calculator_outline,
  "ban outline": Ionicons.ban_outline,
  "person circle outline": Ionicons.person_circle_outline,
  "moon sharp": Ionicons.moon_sharp,
  "battery dead outline": Ionicons.battery_dead_outline,
  "apps": Ionicons.apps,
  "bicycle": Ionicons.bicycle,
  "add circle": Ionicons.add_circle,
  "balloon outline": Ionicons.balloon_outline,
  "flower outline": Ionicons.flower_outline,
  "information circle outline": Ionicons.information_circle_outline,
  "document attach outline": Ionicons.document_attach_outline,
  "arrow down sharp": Ionicons.arrow_down_sharp,
  "pulse sharp": Ionicons.pulse_sharp,
  "musical notes": Ionicons.musical_notes,
  "speedometer sharp": Ionicons.speedometer_sharp,
  "caret down sharp": Ionicons.caret_down_sharp,
  "barcode sharp": Ionicons.barcode_sharp,
  "gift outline": Ionicons.gift_outline,
  "globe": Ionicons.globe,
  "albums outline": Ionicons.albums_outline,
  "invert mode sharp": Ionicons.invert_mode_sharp,
  "chatbox sharp": Ionicons.chatbox_sharp,
  "browsers sharp": Ionicons.browsers_sharp,
  "shield checkmark outline": Ionicons.shield_checkmark_outline,
  "chevron forward": Ionicons.chevron_forward,
  "play forward": Ionicons.play_forward,
  "bookmark": Ionicons.bookmark,
  "logo html5": Ionicons.logo_html5,
  "terminal": Ionicons.terminal,
  "musical note outline": Ionicons.musical_note_outline,
  "tablet portrait": Ionicons.tablet_portrait,
  "flash off outline": Ionicons.flash_off_outline,
  "female": Ionicons.female,
  "library": Ionicons.library,
  "logo steam": Ionicons.logo_steam,
  "chatbubbles": Ionicons.chatbubbles,
  "color fill outline": Ionicons.color_fill_outline,
  "caret back circle outline": Ionicons.caret_back_circle_outline,
  "code outline": Ionicons.code_outline,
  "cafe outline": Ionicons.cafe_outline,
  "sunny": Ionicons.sunny,
  "menu outline": Ionicons.menu_outline,
  "logo playstation": Ionicons.logo_playstation,
  "radio sharp": Ionicons.radio_sharp,
  "medical sharp": Ionicons.medical_sharp,
  "barbell outline": Ionicons.barbell_outline,
  "share sharp": Ionicons.share_sharp,
  "logo sass": Ionicons.logo_sass,
  "chatbubble ellipses sharp": Ionicons.chatbubble_ellipses_sharp,
  "golf": Ionicons.golf,
  "keypad outline": Ionicons.keypad_outline,
  "flower": Ionicons.flower,
  "cloudy night outline": Ionicons.cloudy_night_outline,
  "bag outline": Ionicons.bag_outline,
  "options sharp": Ionicons.options_sharp,
  "crop outline": Ionicons.crop_outline,
  "scan circle sharp": Ionicons.scan_circle_sharp,
  "sparkles outline": Ionicons.sparkles_outline,
  "volume high": Ionicons.volume_high,
  "refresh sharp": Ionicons.refresh_sharp,
  "at circle outline": Ionicons.at_circle_outline,
  "flash": Ionicons.flash,
  "leaf": Ionicons.leaf,
  "business outline": Ionicons.business_outline,
  "log out outline": Ionicons.log_out_outline,
  "eyedrop": Ionicons.eyedrop,
  "flash off": Ionicons.flash_off,
  "heart circle outline": Ionicons.heart_circle_outline,
  "logo ionitron": Ionicons.logo_ionitron,
  "timer outline": Ionicons.timer_outline,
  "caret up outline": Ionicons.caret_up_outline,
  "Ionicons battery full": Ionicons.battery_full,
  "document text sharp": Ionicons.document_text_sharp,
  "man": Ionicons.man,
  "baseball outline": Ionicons.baseball_outline,
  "footsteps outline": Ionicons.footsteps_outline,
  "remove circle outline": Ionicons.remove_circle_outline,
  "partly sunny outline": Ionicons.partly_sunny_outline,
  "scan": Ionicons.scan,
  "radio button on outline": Ionicons.radio_button_on_outline,
  "tennisball": Ionicons.tennisball,
  "american football": Ionicons.american_football,
  "caret back outline": Ionicons.caret_back_outline,
  "documents": Ionicons.documents,
  "alert circle sharp": Ionicons.alert_circle_sharp,
  "print outline": Ionicons.print_outline,
  "logo facebook": Ionicons.logo_facebook,
  "home sharp": Ionicons.home_sharp,
  "folder sharp": Ionicons.folder_sharp,
  "star half": Ionicons.star_half,
  "logo microsoft": Ionicons.logo_microsoft,
  "phone portrait sharp": Ionicons.phone_portrait_sharp,
  "funnel outline": Ionicons.funnel_outline,
  "location": Ionicons.location,
  "ellipsis horizontal": Ionicons.ellipsis_horizontal,
  "logo electron": Ionicons.logo_electron,
  "sunny outline": Ionicons.sunny_outline,
  "mic": Ionicons.mic,
  "logo twitch": Ionicons.logo_twitch,
  "flashlight": Ionicons.flashlight,
  "videocam": Ionicons.videocam,
  "help sharp": Ionicons.help_sharp,
  "caret down circle outline": Ionicons.caret_down_circle_outline,
  "volume off sharp": Ionicons.volume_off_sharp,
  "contrast outline": Ionicons.contrast_outline,
  "trash bin sharp": Ionicons.trash_bin_sharp,
  "close circle": Ionicons.close_circle,
  "contrast sharp": Ionicons.contrast_sharp,
  "cloud upload outline": Ionicons.cloud_upload_outline,
  "locate outline": Ionicons.locate_outline,
  "terminal outline": Ionicons.terminal_outline,
  "duplicate sharp": Ionicons.duplicate_sharp,
  "headset": Ionicons.headset,
  "person add": Ionicons.person_add,
  "skull": Ionicons.skull,
  "today outline": Ionicons.today_outline,
  "ellipse": Ionicons.ellipse,
  "repeat": Ionicons.repeat,
  "logo figma": Ionicons.logo_figma,
  "pause": Ionicons.pause,
  "duplicate": Ionicons.duplicate,
  "filter": Ionicons.filter,
  "chevron down": Ionicons.chevron_down,
  "caret back sharp": Ionicons.caret_back_sharp,
  "share": Ionicons.share,
  "caret forward sharp": Ionicons.caret_forward_sharp,
  "git compare": Ionicons.git_compare,
  "unlink": Ionicons.unlink,
  "fitness sharp": Ionicons.fitness_sharp,
  "trophy sharp": Ionicons.trophy_sharp,
  "filter sharp": Ionicons.filter_sharp,
  "caret up": Ionicons.caret_up,
  "trail sign sharp": Ionicons.trail_sign_sharp,
  "easel": Ionicons.easel,
  "image sharp": Ionicons.image_sharp,
  "cellular outline": Ionicons.cellular_outline,
  "unlink sharp": Ionicons.unlink_sharp,
  "musical note sharp": Ionicons.musical_note_sharp,
  "arrow redo sharp": Ionicons.arrow_redo_sharp,
  "volume off": Ionicons.volume_off,
  "radio button on": Ionicons.radio_button_on,
  "heart dislike circle outline": Ionicons.heart_dislike_circle_outline,
  "mail unread sharp": Ionicons.mail_unread_sharp,
  "logo google playstore": Ionicons.logo_google_playstore,
  "git compare outline": Ionicons.git_compare_outline,
  "person remove": Ionicons.person_remove,
  "notifications off sharp": Ionicons.notifications_off_sharp,
  "telescope outline": Ionicons.telescope_outline,
  "brush outline": Ionicons.brush_outline,
  "bus sharp": Ionicons.bus_sharp,
  "camera reverse sharp": Ionicons.camera_reverse_sharp,
  "laptop outline": Ionicons.laptop_outline,
  "male female": Ionicons.male_female,
  "beaker outline": Ionicons.beaker_outline,
  "volume medium sharp": Ionicons.volume_medium_sharp,
  "logo pinterest": Ionicons.logo_pinterest,
  "caret up circle sharp": Ionicons.caret_up_circle_sharp,
  "color filter sharp": Ionicons.color_filter_sharp,
  "people": Ionicons.people,
  "school": Ionicons.school,
  "ticket outline": Ionicons.ticket_outline,
  "build sharp": Ionicons.build_sharp,
  "archive sharp": Ionicons.archive_sharp,
  "folder open": Ionicons.folder_open,
  "shield checkmark sharp": Ionicons.shield_checkmark_sharp,
  "arrow forward": Ionicons.arrow_forward,
  "caret forward circle outline": Ionicons.caret_forward_circle_outline,
  "git merge sharp": Ionicons.git_merge_sharp,
  "tv": Ionicons.tv,
  "heart sharp": Ionicons.heart_sharp,
  "push outline": Ionicons.push_outline,
  "bug sharp": Ionicons.bug_sharp,
  "caret down": Ionicons.caret_down,
  "chevron back": Ionicons.chevron_back,
  "female outline": Ionicons.female_outline,
  "logo amplify": Ionicons.logo_amplify,
  "trash outline": Ionicons.trash_outline,
  "information sharp": Ionicons.information_sharp,
  "watch": Ionicons.watch,
  "magnet sharp": Ionicons.magnet_sharp,
  "dice sharp": Ionicons.dice_sharp,
  "restaurant sharp": Ionicons.restaurant_sharp,
  "glasses outline": Ionicons.glasses_outline,
  "timer sharp": Ionicons.timer_sharp,
  "file tray full": Ionicons.file_tray_full,
  "ear": Ionicons.ear,
  "nuclear sharp": Ionicons.nuclear_sharp,
  "recording sharp": Ionicons.recording_sharp,
  "hardware chip": Ionicons.hardware_chip,
  "volume medium": Ionicons.volume_medium,
  "infinite sharp": Ionicons.infinite_sharp,
  "person outline": Ionicons.person_outline,
  "arrow forward sharp": Ionicons.arrow_forward_sharp,
  "trending down outline": Ionicons.trending_down_outline,
  "trash bin outline": Ionicons.trash_bin_outline,
  "pause outline": Ionicons.pause_outline,
  "diamond sharp": Ionicons.diamond_sharp,
  "reload circle": Ionicons.reload_circle,
  "open outline": Ionicons.open_outline,
  "pint outline": Ionicons.pint_outline,
  "brush sharp": Ionicons.brush_sharp,
  "skull sharp": Ionicons.skull_sharp,
  "bowling ball": Ionicons.bowling_ball,
  "power sharp": Ionicons.power_sharp,
  "reader sharp": Ionicons.reader_sharp,
  "heart dislike outline": Ionicons.heart_dislike_outline,
  "folder open outline": Ionicons.folder_open_outline,
  "document lock outline": Ionicons.document_lock_outline,
  "cart": Ionicons.cart,
  "train sharp": Ionicons.train_sharp,
  "play back circle sharp": Ionicons.play_back_circle_sharp,
  "color fill sharp": Ionicons.color_fill_sharp,
  "logo euro": Ionicons.logo_euro,
  "play circle sharp": Ionicons.play_circle_sharp,
  "bulb": Ionicons.bulb,
  "map sharp": Ionicons.map_sharp,
  "tablet portrait outline": Ionicons.tablet_portrait_outline,
  "receipt sharp": Ionicons.receipt_sharp,
  "arrow up outline": Ionicons.arrow_up_outline,
  "caret forward": Ionicons.caret_forward,
  "cut sharp": Ionicons.cut_sharp,
  "people sharp": Ionicons.people_sharp,
  "cut outline": Ionicons.cut_outline,
  "logo tux": Ionicons.logo_tux,
  "options": Ionicons.options,
  "lock closed sharp": Ionicons.lock_closed_sharp,
  "flask sharp": Ionicons.flask_sharp,
  "copy outline": Ionicons.copy_outline,
  "Ionicons business": Ionicons.business,
  "document lock": Ionicons.document_lock,
  "move sharp": Ionicons.move_sharp,
  "accessibility outline": Ionicons.accessibility_outline,
  "play skip forward circle sharp": Ionicons.play_skip_forward_circle_sharp,
  "subway": Ionicons.subway,
  "thumbs up outline": Ionicons.thumbs_up_outline,
  "barcode": Ionicons.barcode,
  "thermometer sharp": Ionicons.thermometer_sharp,
  "logo apple appstore": Ionicons.logo_apple_appstore,
  "paw outline": Ionicons.paw_outline,
  "logo bitbucket": Ionicons.logo_bitbucket,
  "bag": Ionicons.bag,
  "grid sharp": Ionicons.grid_sharp,
  "barbell": Ionicons.barbell,
  "bandage sharp": Ionicons.bandage_sharp,
  "Ionicons bed": Ionicons.bed,
  "alert": Ionicons.alert,
  "tennisball outline": Ionicons.tennisball_outline,
  "logo javascript": Ionicons.logo_javascript,
  "expand": Ionicons.expand,
  "ellipsis horizontal circle": Ionicons.ellipsis_horizontal_circle,
  "logo laravel": Ionicons.logo_laravel,
  "return up forward outline": Ionicons.return_up_forward_outline,
  "chatbox": Ionicons.chatbox,
  "pause sharp": Ionicons.pause_sharp,
  "cash outline": Ionicons.cash_outline,
  "caret up circle": Ionicons.caret_up_circle,
  "chatbubbles sharp": Ionicons.chatbubbles_sharp,
  "document text": Ionicons.document_text,
  "logo behance": Ionicons.logo_behance,
  "aperture outline": Ionicons.aperture_outline,
  "chevron up circle sharp": Ionicons.chevron_up_circle_sharp,
  "close circle outline": Ionicons.close_circle_outline,
  "log in outline": Ionicons.log_in_outline,
  "logo buffer": Ionicons.logo_buffer,
  "ellipsis horizontal sharp": Ionicons.ellipsis_horizontal_sharp,
  "color palette": Ionicons.color_palette,
  "chevron back circle outline": Ionicons.chevron_back_circle_outline,
  "chevron back outline": Ionicons.chevron_back_outline,
  "logo tumblr": Ionicons.logo_tumblr,
  "fast food": Ionicons.fast_food,
  "ellipsis vertical circle sharp": Ionicons.ellipsis_vertical_circle_sharp,
  "female sharp": Ionicons.female_sharp,
  "flame sharp": Ionicons.flame_sharp,
  "cart sharp": Ionicons.cart_sharp,
  "document outline": Ionicons.document_outline,
  "pause circle": Ionicons.pause_circle,
  "print sharp": Ionicons.print_sharp,
  "help outline": Ionicons.help_outline,
  "cube sharp": Ionicons.cube_sharp,
  "logo web component": Ionicons.logo_web_component,
  "film outline": Ionicons.film_outline,
  "wine": Ionicons.wine,
  "heart half outline": Ionicons.heart_half_outline,
  "basket sharp": Ionicons.basket_sharp,
  "eyedrop sharp": Ionicons.eyedrop_sharp,
  "happy": Ionicons.happy,
  "dice": Ionicons.dice,
  "arrow back circle outline": Ionicons.arrow_back_circle_outline,
  "film": Ionicons.film,
  "battery full sharp": Ionicons.battery_full_sharp,
  "calendar number sharp": Ionicons.calendar_number_sharp,
  "logo google": Ionicons.logo_google,
  "at": Ionicons.at,
  "arrow forward circle sharp": Ionicons.arrow_forward_circle_sharp,
  "chevron down sharp": Ionicons.chevron_down_sharp,
  "hardware chip sharp": Ionicons.hardware_chip_sharp,
  "play outline": Ionicons.play_outline,
  "qr code": Ionicons.qr_code,
  "alarm sharp": Ionicons.alarm_sharp,
  "diamond outline": Ionicons.diamond_outline,
  "cloud sharp": Ionicons.cloud_sharp,
  "keypad sharp": Ionicons.keypad_sharp,
  "share social": Ionicons.share_social,
  "triangle outline": Ionicons.triangle_outline,
  "caret down outline": Ionicons.caret_down_outline,
  "ellipsis vertical sharp": Ionicons.ellipsis_vertical_sharp,
  "cellular sharp": Ionicons.cellular_sharp,
  "chatbox ellipses outline": Ionicons.chatbox_ellipses_outline,
  "refresh outline": Ionicons.refresh_outline,
  "documents sharp": Ionicons.documents_sharp,
  "add circle outline": Ionicons.add_circle_outline,
  "skull outline": Ionicons.skull_outline,
  "images": Ionicons.images,
  "logo stencil": Ionicons.logo_stencil,
  "caret up sharp": Ionicons.caret_up_sharp,
  "logo nodejs": Ionicons.logo_nodejs,
  "eye outline": Ionicons.eye_outline,
  "heart half sharp": Ionicons.heart_half_sharp,
  "resize outline": Ionicons.resize_outline,
  "swap vertical outline": Ionicons.swap_vertical_outline,
  "cloud download outline": Ionicons.cloud_download_outline,
  "reorder three sharp": Ionicons.reorder_three_sharp,
  "search outline": Ionicons.search_outline,
  "eye off sharp": Ionicons.eye_off_sharp,
  "checkmark": Ionicons.checkmark,
  "cloudy night sharp": Ionicons.cloudy_night_sharp,
  "bookmark outline": Ionicons.bookmark_outline,
  "man sharp": Ionicons.man_sharp,
  "caret forward outline": Ionicons.caret_forward_outline,
  "remove outline": Ionicons.remove_outline,
  "disc outline": Ionicons.disc_outline,
  "journal": Ionicons.journal,
  "logo apple": Ionicons.logo_apple,
  "snow outline": Ionicons.snow_outline,
  "cloud download sharp": Ionicons.cloud_download_sharp,
  "basket": Ionicons.basket,
  "extension puzzle": Ionicons.extension_puzzle,
  "bag handle": Ionicons.bag_handle,
  "document": Ionicons.document,
  "play sharp": Ionicons.play_sharp,
  "enter": Ionicons.enter,
  "bandage outline": Ionicons.bandage_outline,
  "bar chart": Ionicons.bar_chart,
  "logo ionic": Ionicons.logo_ionic,
  "sparkles sharp": Ionicons.sparkles_sharp,
  "sad outline": Ionicons.sad_outline,
  "library sharp": Ionicons.library_sharp,
  "return down forward outline": Ionicons.return_down_forward_outline,
  "logo angular": Ionicons.logo_angular,
  "library outline": Ionicons.library_outline,
  "caret down circle": Ionicons.caret_down_circle,
  "play skip forward circle": Ionicons.play_skip_forward_circle,
  "triangle": Ionicons.triangle,
  "stats chart outline": Ionicons.stats_chart_outline,
  "logo react": Ionicons.logo_react,
  "backspace sharp": Ionicons.backspace_sharp,
  "cube outline": Ionicons.cube_outline,
  "sync circle": Ionicons.sync_circle,
  "diamond": Ionicons.diamond,
  "basketball sharp": Ionicons.basketball_sharp,
  "notifications circle sharp": Ionicons.notifications_circle_sharp,
  "folder": Ionicons.folder,
  "open sharp": Ionicons.open_sharp,
  "bed outline": Ionicons.bed_outline,
  "clipboard": Ionicons.clipboard,
  "school sharp": Ionicons.school_sharp,
  "arrow redo circle": Ionicons.arrow_redo_circle,
  "ellipsis vertical circle outline": Ionicons.ellipsis_vertical_circle_outline,
  "beaker": Ionicons.beaker,
  "logo skype": Ionicons.logo_skype,
  "pint sharp": Ionicons.pint_sharp,
  "pin outline": Ionicons.pin_outline,
  "expand outline": Ionicons.expand_outline,
  "play skip back outline": Ionicons.play_skip_back_outline,
  "happy sharp": Ionicons.happy_sharp,
  "headset outline": Ionicons.headset_outline,
  "copy": Ionicons.copy,
  "crop": Ionicons.crop,
  "arrow forward outline": Ionicons.arrow_forward_outline,
  "color filter outline": Ionicons.color_filter_outline,
  "refresh": Ionicons.refresh,
  "logo amazon": Ionicons.logo_amazon,
  "star": Ionicons.star,
  "exit outline": Ionicons.exit_outline,
  "image outline": Ionicons.image_outline,
  "code slash outline": Ionicons.code_slash_outline,
  "disc": Ionicons.disc,
  "mic off circle sharp": Ionicons.mic_off_circle_sharp,
  "moon outline": Ionicons.moon_outline,
  "headset sharp": Ionicons.headset_sharp,
  "text sharp": Ionicons.text_sharp,
  "trail sign": Ionicons.trail_sign,
  "rocket": Ionicons.rocket,
  "star half sharp": Ionicons.star_half_sharp,
  "sad sharp": Ionicons.sad_sharp,
  "help buoy": Ionicons.help_buoy,
  "funnel": Ionicons.funnel,
  "logo vk": Ionicons.logo_vk,
  "beer outline": Ionicons.beer_outline,
  "filter outline": Ionicons.filter_outline,
  "construct": Ionicons.construct,
  "football outline": Ionicons.football_outline,
  "play forward outline": Ionicons.play_forward_outline,
  "cloud outline": Ionicons.cloud_outline,
  "journal sharp": Ionicons.journal_sharp,
  "people circle sharp": Ionicons.people_circle_sharp,
  "tablet landscape outline": Ionicons.tablet_landscape_outline,
  "egg outline": Ionicons.egg_outline,
  "shield outline": Ionicons.shield_outline,
  "finger print outline": Ionicons.finger_print_outline,
  "phone landscape sharp": Ionicons.phone_landscape_sharp,
  "ellipsis horizontal circle outline":
      Ionicons.ellipsis_horizontal_circle_outline,
  "build": Ionicons.build,
  "shield half sharp": Ionicons.shield_half_sharp,
  "bulb sharp": Ionicons.bulb_sharp,
  "pie chart": Ionicons.pie_chart,
  "information circle": Ionicons.information_circle,
  "heart": Ionicons.heart,
  "megaphone": Ionicons.megaphone,
  "lock open outline": Ionicons.lock_open_outline,
  "extension puzzle outline": Ionicons.extension_puzzle_outline,
  "cash": Ionicons.cash,
  "menu": Ionicons.menu,
  "power outline": Ionicons.power_outline,
  "cloud": Ionicons.cloud,
  "logo codepen": Ionicons.logo_codepen,
  "arrow back circle sharp": Ionicons.arrow_back_circle_sharp,
  "arrow up sharp": Ionicons.arrow_up_sharp,
  "alarm": Ionicons.alarm,
  "lock closed outline": Ionicons.lock_closed_outline,
  "camera sharp": Ionicons.camera_sharp,
  "logo vercel": Ionicons.logo_vercel,
  "alert sharp": Ionicons.alert_sharp,
  "wine outline": Ionicons.wine_outline,
  "infinite outline": Ionicons.infinite_outline,
  "clipboard sharp": Ionicons.clipboard_sharp,
  "bonfire outline": Ionicons.bonfire_outline,
  "boat sharp": Ionicons.boat_sharp,
  "logo alipay": Ionicons.logo_alipay,
  "cloud offline outline": Ionicons.cloud_offline_outline,
  "storefront outline": Ionicons.storefront_outline,
  "watch sharp": Ionicons.watch_sharp,
  "shield sharp": Ionicons.shield_sharp,
  "swap vertical sharp": Ionicons.swap_vertical_sharp,
  "arrow undo outline": Ionicons.arrow_undo_outline,
  "today sharp": Ionicons.today_sharp,
  "help circle sharp": Ionicons.help_circle_sharp,
  "card sharp": Ionicons.card_sharp,
  "woman outline": Ionicons.woman_outline,
  "code download sharp": Ionicons.code_download_sharp,
  "pin": Ionicons.pin,
  "desktop": Ionicons.desktop,
  "newspaper outline": Ionicons.newspaper_outline,
  "text": Ionicons.text,
  "logo flickr": Ionicons.logo_flickr,
  "musical notes sharp": Ionicons.musical_notes_sharp,
  "logo yen": Ionicons.logo_yen,
  "time sharp": Ionicons.time_sharp,
  "stop circle outline": Ionicons.stop_circle_outline,
  "albums sharp": Ionicons.albums_sharp,
  "logo dribbble": Ionicons.logo_dribbble,
  "shuffle": Ionicons.shuffle,
  "camera reverse": Ionicons.camera_reverse,
  "folder open sharp": Ionicons.folder_open_sharp,
  "chatbubble outline": Ionicons.chatbubble_outline,
  "code sharp": Ionicons.code_sharp,
  "egg": Ionicons.egg,
  "chatbubble": Ionicons.chatbubble,
  "eye off": Ionicons.eye_off,
  "people circle": Ionicons.people_circle,
  "sunny sharp": Ionicons.sunny_sharp,
  "ribbon outline": Ionicons.ribbon_outline,
  "power": Ionicons.power,
  "swap horizontal outline": Ionicons.swap_horizontal_outline,
  "cloud done sharp": Ionicons.cloud_done_sharp,
  "server sharp": Ionicons.server_sharp,
  "rainy sharp": Ionicons.rainy_sharp,
  "play skip back circle": Ionicons.play_skip_back_circle,
  "bag remove sharp": Ionicons.bag_remove_sharp,
  "build outline": Ionicons.build_outline,
  "flame outline": Ionicons.flame_outline,
  "play back sharp": Ionicons.play_back_sharp,
  "backspace outline": Ionicons.backspace_outline,
  "logo vimeo": Ionicons.logo_vimeo,
  "star outline": Ionicons.star_outline,
  "exit": Ionicons.exit,
  "resize sharp": Ionicons.resize_sharp,
  "albums": Ionicons.albums,
  "checkmark circle sharp": Ionicons.checkmark_circle_sharp,
  "hourglass sharp": Ionicons.hourglass_sharp,
  "flashlight outline": Ionicons.flashlight_outline,
  "code download outline": Ionicons.code_download_outline,
  "chevron forward sharp": Ionicons.chevron_forward_sharp,
  "bicycle outline": Ionicons.bicycle_outline,
  "play skip back circle outline": Ionicons.play_skip_back_circle_outline,
  "notifications off": Ionicons.notifications_off,
  "ribbon": Ionicons.ribbon,
  "chevron up": Ionicons.chevron_up,
  "exit sharp": Ionicons.exit_sharp,
  "file tray full outline": Ionicons.file_tray_full_outline,
  "arrow redo circle sharp": Ionicons.arrow_redo_circle_sharp,
  "wallet": Ionicons.wallet,
  "reorder three": Ionicons.reorder_three,
  "earth outline": Ionicons.earth_outline,
  "share outline": Ionicons.share_outline,
  "stop outline": Ionicons.stop_outline,
  "cog outline": Ionicons.cog_outline,
  "remove circle sharp": Ionicons.remove_circle_sharp,
  "recording outline": Ionicons.recording_outline,
  "pause circle sharp": Ionicons.pause_circle_sharp,
  "alarm outline": Ionicons.alarm_outline,
  "nutrition outline": Ionicons.nutrition_outline,
  "shield half outline": Ionicons.shield_half_outline,
  "camera reverse outline": Ionicons.camera_reverse_outline,
  "volume low outline": Ionicons.volume_low_outline,
  "logo venmo": Ionicons.logo_venmo,
  "git pull request sharp": Ionicons.git_pull_request_sharp,
  "podium sharp": Ionicons.podium_sharp,
  "chatbubble ellipses outline": Ionicons.chatbubble_ellipses_outline,
  "bulb outline": Ionicons.bulb_outline,
  "apps sharp": Ionicons.apps_sharp,
  "arrow down": Ionicons.arrow_down,
  "code slash sharp": Ionicons.code_slash_sharp,
  "play skip forward sharp": Ionicons.play_skip_forward_sharp,
  "pause circle outline": Ionicons.pause_circle_outline,
  "prism": Ionicons.prism,
  "shuffle sharp": Ionicons.shuffle_sharp,
  "medal sharp": Ionicons.medal_sharp,
  "stop": Ionicons.stop,
  "thumbs up sharp": Ionicons.thumbs_up_sharp,
  "navigate outline": Ionicons.navigate_outline,
  "logo stackoverflow": Ionicons.logo_stackoverflow,
  "clipboard outline": Ionicons.clipboard_outline,
  "logo firefox": Ionicons.logo_firefox,
  "git branch sharp": Ionicons.git_branch_sharp,
  "body outline": Ionicons.body_outline,
  "cloud circle": Ionicons.cloud_circle,
  "square": Ionicons.square,
  "call sharp": Ionicons.call_sharp,
  "close outline": Ionicons.close_outline,
  "logo closed captioning": Ionicons.logo_closed_captioning,
  "battery full outline": Ionicons.battery_full_outline,
  "images sharp": Ionicons.images_sharp,
  "footsteps": Ionicons.footsteps,
  "boat": Ionicons.boat,
  "code": Ionicons.code,
  "bag check": Ionicons.bag_check,
  "id card sharp": Ionicons.id_card_sharp,
  "mic sharp": Ionicons.mic_sharp,
  "eye sharp": Ionicons.eye_sharp,
  "log out": Ionicons.log_out,
  "radio button off outline": Ionicons.radio_button_off_outline,
  "logo snapchat": Ionicons.logo_snapchat,
  "flame": Ionicons.flame,
  "logo markdown": Ionicons.logo_markdown,
  "ice cream outline": Ionicons.ice_cream_outline,
  "logo firebase": Ionicons.logo_firebase,
  "checkmark done circle outline": Ionicons.checkmark_done_circle_outline,
  "rose sharp": Ionicons.rose_sharp,
  "logo apple ar": Ionicons.logo_apple_ar,
  "settings outline": Ionicons.settings_outline,
  "help circle outline": Ionicons.help_circle_outline,
  "reload circle outline": Ionicons.reload_circle_outline,
  "battery dead sharp": Ionicons.battery_dead_sharp,
  "logo edge": Ionicons.logo_edge,
  "logo gitlab": Ionicons.logo_gitlab,
  "logo twitter": Ionicons.logo_twitter,
  "bowling ball outline": Ionicons.bowling_ball_outline,
  "calendar sharp": Ionicons.calendar_sharp,
  "walk": Ionicons.walk,
  "eye off outline": Ionicons.eye_off_outline,
  "briefcase sharp": Ionicons.briefcase_sharp,
  "heart dislike circle": Ionicons.heart_dislike_circle,
  "balloon": Ionicons.balloon,
  "bookmarks sharp": Ionicons.bookmarks_sharp,
  "phone landscape": Ionicons.phone_landscape,
  "git branch": Ionicons.git_branch,
  "compass": Ionicons.compass,
  "game controller": Ionicons.game_controller,
  "bookmarks outline": Ionicons.bookmarks_outline,
  "receipt": Ionicons.receipt,
  "male female outline": Ionicons.male_female_outline,
  "list": Ionicons.list,
  "images outline": Ionicons.images_outline,
  "beer sharp": Ionicons.beer_sharp,
  "bag check outline": Ionicons.bag_check_outline,
  "arrow back sharp": Ionicons.arrow_back_sharp,
  "pencil": Ionicons.pencil,
  "text outline": Ionicons.text_outline,
  "eye": Ionicons.eye,
  "download outline": Ionicons.download_outline,
  "navigate circle": Ionicons.navigate_circle,
  "thunderstorm sharp": Ionicons.thunderstorm_sharp,
  "american football outline": Ionicons.american_football_outline,
  "bookmarks": Ionicons.bookmarks,
  "shirt sharp": Ionicons.shirt_sharp,
  "shirt outline": Ionicons.shirt_outline,
  "chevron down circle outline": Ionicons.chevron_down_circle_outline,
  "medical": Ionicons.medical,
  "color filter": Ionicons.color_filter,
  "logo python": Ionicons.logo_python,
  "paper plane": Ionicons.paper_plane,
  "medkit": Ionicons.medkit,
  "Ionicons call": Ionicons.call,
  "flower sharp": Ionicons.flower_sharp,
  "calendar clear": Ionicons.calendar_clear,
  "walk sharp": Ionicons.walk_sharp,
  "heart outline": Ionicons.heart_outline,
  "cloudy night": Ionicons.cloudy_night,
  "play skip back circle sharp": Ionicons.play_skip_back_circle_sharp,
  "earth": Ionicons.earth,
  "volume low sharp": Ionicons.volume_low_sharp,
  "thunderstorm": Ionicons.thunderstorm,
  "bag remove outline": Ionicons.bag_remove_outline,
  "videocam off sharp": Ionicons.videocam_off_sharp,
  "remove sharp": Ionicons.remove_sharp,
  "time outline": Ionicons.time_outline,
  "folder outline": Ionicons.folder_outline,
  "basket outline": Ionicons.basket_outline,
  "walk outline": Ionicons.walk_outline,
  "stop sharp": Ionicons.stop_sharp,
  "duplicate outline": Ionicons.duplicate_outline,
  "stopwatch outline": Ionicons.stopwatch_outline,
  "repeat outline": Ionicons.repeat_outline,
  "desktop sharp": Ionicons.desktop_sharp,
  "hand right sharp": Ionicons.hand_right_sharp,
  "nuclear": Ionicons.nuclear,
  "ear sharp": Ionicons.ear_sharp,
  "phone portrait outline": Ionicons.phone_portrait_outline,
  "finger print": Ionicons.finger_print,
  "mail open outline": Ionicons.mail_open_outline,
  "phone landscape outline": Ionicons.phone_landscape_outline,
  "heart half": Ionicons.heart_half,
  "play": Ionicons.play,
  "play forward circle sharp": Ionicons.play_forward_circle_sharp,
  "snow sharp": Ionicons.snow_sharp,
  "compass outline": Ionicons.compass_outline,
  "checkmark done circle": Ionicons.checkmark_done_circle,
  "stopwatch sharp": Ionicons.stopwatch_sharp,
  "paper plane sharp": Ionicons.paper_plane_sharp,
  "bonfire sharp": Ionicons.bonfire_sharp,
  "shield checkmark": Ionicons.shield_checkmark,
  "navigate circle sharp": Ionicons.navigate_circle_sharp,
  "videocam off outline": Ionicons.videocam_off_outline,
  "subway sharp": Ionicons.subway_sharp,
  "logo linkedin": Ionicons.logo_linkedin,
  "bag check sharp": Ionicons.bag_check_sharp,
  "logo docker": Ionicons.logo_docker,
  "Ionicons water": Ionicons.water,
  "analytics sharp": Ionicons.analytics_sharp,
  "business sharp": Ionicons.business_sharp,
  "rainy": Ionicons.rainy,
  "magnet": Ionicons.magnet,
  "medkit outline": Ionicons.medkit_outline,
  "play forward circle outline": Ionicons.play_forward_circle_outline,
  "ellipse outline": Ionicons.ellipse_outline,
  "logo tiktok": Ionicons.logo_tiktok,
  "body sharp": Ionicons.body_sharp,
  "cafe": Ionicons.cafe,
  "logo hackernews": Ionicons.logo_hackernews,
  "male outline": Ionicons.male_outline,
  "mail outline": Ionicons.mail_outline,
  "location outline": Ionicons.location_outline,
  "today": Ionicons.today,
  "invert mode": Ionicons.invert_mode,
  "caret forward circle sharp": Ionicons.caret_forward_circle_sharp,
  "notifications circle outline": Ionicons.notifications_circle_outline,
  "infinite": Ionicons.infinite,
  "color wand": Ionicons.color_wand,
  "book outline": Ionicons.book_outline,
  "document sharp": Ionicons.document_sharp,
  "warning": Ionicons.warning,
  "pizza": Ionicons.pizza,
  "Ionicons moon": Ionicons.moon,
  "transgender outline": Ionicons.transgender_outline,
  "american football sharp": Ionicons.american_football_sharp,
  "arrow up": Ionicons.arrow_up,
  "flag outline": Ionicons.flag_outline,
  "gift sharp": Ionicons.gift_sharp,
  "nutrition": Ionicons.nutrition,
  "tablet landscape sharp": Ionicons.tablet_landscape_sharp,
  "thumbs down outline": Ionicons.thumbs_down_outline,
  "pizza outline": Ionicons.pizza_outline,
  "qr code outline": Ionicons.qr_code_outline,
  "information outline": Ionicons.information_outline,
  "planet sharp": Ionicons.planet_sharp,
  "volume high sharp": Ionicons.volume_high_sharp,
  "log in sharp": Ionicons.log_in_sharp,
  "mic off outline": Ionicons.mic_off_outline,
  "game controller outline": Ionicons.game_controller_outline,
  "download sharp": Ionicons.download_sharp,
  "return down back sharp": Ionicons.return_down_back_sharp,
  "card": Ionicons.card,
  "list circle sharp": Ionicons.list_circle_sharp,
  "return up forward": Ionicons.return_up_forward,
  "eyedrop outline": Ionicons.eyedrop_outline,
  "add circle sharp": Ionicons.add_circle_sharp,
  "tablet landscape": Ionicons.tablet_landscape,
  "color fill": Ionicons.color_fill,
  "calendar number": Ionicons.calendar_number,
  "calendar clear outline": Ionicons.calendar_clear_outline,
  "restaurant": Ionicons.restaurant,
  "trending up sharp": Ionicons.trending_up_sharp,
  "play skip back sharp": Ionicons.play_skip_back_sharp,
  "basketball": Ionicons.basketball,
  "filter circle sharp": Ionicons.filter_circle_sharp,
  "alert circle outline": Ionicons.alert_circle_outline,
  "contract outline": Ionicons.contract_outline,
  "golf sharp": Ionicons.golf_sharp,
  "game controller sharp": Ionicons.game_controller_sharp,
  "analytics outline": Ionicons.analytics_outline,
  "cash sharp": Ionicons.cash_sharp,
  "remove circle": Ionicons.remove_circle,
  "arrow down circle": Ionicons.arrow_down_circle,
  "aperture sharp": Ionicons.aperture_sharp,
  "logo deviantart": Ionicons.logo_deviantart,
  "browsers": Ionicons.browsers,
  "telescope": Ionicons.telescope,
  "logo pwa": Ionicons.logo_pwa,
  "airplane sharp": Ionicons.airplane_sharp,
  "bag sharp": Ionicons.bag_sharp,
  "water outline": Ionicons.water_outline,
  "snow": Ionicons.snow,
  "planet": Ionicons.planet,
  "code working outline": Ionicons.code_working_outline,
  "mic off sharp": Ionicons.mic_off_sharp,
  "swap vertical": Ionicons.swap_vertical,
  "thunderstorm outline": Ionicons.thunderstorm_outline,
  "notifications circle": Ionicons.notifications_circle,
  "airplane": Ionicons.airplane,
  "notifications off circle": Ionicons.notifications_off_circle,
  "cloud upload": Ionicons.cloud_upload,
  "Ionicons print": Ionicons.print,
  "notifications off circle outline": Ionicons.notifications_off_circle_outline,
  "flash outline": Ionicons.flash_outline,
  "help buoy outline": Ionicons.help_buoy_outline,
  "bus": Ionicons.bus,
  "book": Ionicons.book,
  "person remove sharp": Ionicons.person_remove_sharp,
  "chevron down outline": Ionicons.chevron_down_outline,
  "menu sharp": Ionicons.menu_sharp,
  "stop circle": Ionicons.stop_circle,
  "sync circle outline": Ionicons.sync_circle_outline,
  "scale": Ionicons.scale,
  "arrow up circle": Ionicons.arrow_up_circle,
  "list circle": Ionicons.list_circle,
  "car outline": Ionicons.car_outline,
  "musical notes outline": Ionicons.musical_notes_outline,
  "logo chrome": Ionicons.logo_chrome,
  "share social outline": Ionicons.share_social_outline,
  "ear outline": Ionicons.ear_outline,
  "rocket outline": Ionicons.rocket_outline,
  "reorder four outline": Ionicons.reorder_four_outline,
  "download": Ionicons.download,
  "fitness": Ionicons.fitness,
  "trending down": Ionicons.trending_down,
  "man outline": Ionicons.man_outline,
  "triangle sharp": Ionicons.triangle_sharp,
  "trash bin": Ionicons.trash_bin,
  "ellipsis horizontal outline": Ionicons.ellipsis_horizontal_outline,
  "person add outline": Ionicons.person_add_outline,
  "chevron forward circle": Ionicons.chevron_forward_circle,
  "bluetooth sharp": Ionicons.bluetooth_sharp,
  "finger print sharp": Ionicons.finger_print_sharp,
  "barcode outline": Ionicons.barcode_outline,
  "archive": Ionicons.archive,
  "save outline": Ionicons.save_outline,
  "paw sharp": Ionicons.paw_sharp,
  "logo paypal": Ionicons.logo_paypal,
  "pricetag sharp": Ionicons.pricetag_sharp,
  "body": Ionicons.body,
  "play back outline": Ionicons.play_back_outline,
  "radio button off sharp": Ionicons.radio_button_off_sharp,
  "star half outline": Ionicons.star_half_outline,
  "play forward sharp": Ionicons.play_forward_sharp,
  "logo youtube": Ionicons.logo_youtube,
  "alert circle": Ionicons.alert_circle,
  "tablet portrait sharp": Ionicons.tablet_portrait_sharp,
  "information": Ionicons.information,
  "chevron back circle sharp": Ionicons.chevron_back_circle_sharp,
  "git merge outline": Ionicons.git_merge_outline,
  "send": Ionicons.send,
  "trending up outline": Ionicons.trending_up_outline,
  "scan outline": Ionicons.scan_outline,
  "cut": Ionicons.cut,
  "file tray outline": Ionicons.file_tray_outline,
  "navigate sharp": Ionicons.navigate_sharp,
  "checkmark outline": Ionicons.checkmark_outline,
  "alert outline": Ionicons.alert_outline,
  "stats chart sharp": Ionicons.stats_chart_sharp,
  "pricetags outline": Ionicons.pricetags_outline,
  "shapes outline": Ionicons.shapes_outline,
  "shuffle outline": Ionicons.shuffle_outline,
  "help": Ionicons.help,
  "person": Ionicons.person,
  "git compare sharp": Ionicons.git_compare_sharp,
  "git pull request outline": Ionicons.git_pull_request_outline,
  "compass sharp": Ionicons.compass_sharp,
  "speedometer outline": Ionicons.speedometer_outline,
  "checkbox outline": Ionicons.checkbox_outline,
  "git pull request": Ionicons.git_pull_request,
  "radio button off": Ionicons.radio_button_off,
  "open": Ionicons.open,
  "water sharp": Ionicons.water_sharp,
  "chevron forward outline": Ionicons.chevron_forward_outline,
  "cloudy": Ionicons.cloudy,
  "layers outline": Ionicons.layers_outline,
  "heart dislike circle sharp": Ionicons.heart_dislike_circle_sharp,
  "chatbubble ellipses": Ionicons.chatbubble_ellipses,
  "logo slack": Ionicons.logo_slack,
  "reorder four": Ionicons.reorder_four,
  "file tray stacked outline": Ionicons.file_tray_stacked_outline,
  "notifications outline": Ionicons.notifications_outline,
  "logo android": Ionicons.logo_android,
  "calendar number outline": Ionicons.calendar_number_outline,
  "bluetooth": Ionicons.bluetooth,
  "mail open sharp": Ionicons.mail_open_sharp,
  "car sport": Ionicons.car_sport,
  "beaker sharp": Ionicons.beaker_sharp,
  "location sharp": Ionicons.location_sharp,
  "paw": Ionicons.paw,
  "partly sunny": Ionicons.partly_sunny,
  "umbrella outline": Ionicons.umbrella_outline,
  "logo instagram": Ionicons.logo_instagram,
  "color palette outline": Ionicons.color_palette_outline,
  "hammer outline": Ionicons.hammer_outline,
  "battery half": Ionicons.battery_half,
  "cloud done outline": Ionicons.cloud_done_outline,
  "play back circle outline": Ionicons.play_back_circle_outline,
  "enter outline": Ionicons.enter_outline,
  "male sharp": Ionicons.male_sharp,
  "car": Ionicons.car,
  "notifications": Ionicons.notifications,
  "play circle": Ionicons.play_circle,
  "arrow undo circle sharp": Ionicons.arrow_undo_circle_sharp,
  "transgender": Ionicons.transgender,
  "newspaper sharp": Ionicons.newspaper_sharp,
  "ellipsis vertical outline": Ionicons.ellipsis_vertical_outline,
  "thumbs up": Ionicons.thumbs_up,
  "trash sharp": Ionicons.trash_sharp,
  "speedometer": Ionicons.speedometer,
  "color palette sharp": Ionicons.color_palette_sharp,
  "cloud circle outline": Ionicons.cloud_circle_outline,
  "layers sharp": Ionicons.layers_sharp,
  "telescope sharp": Ionicons.telescope_sharp,
  "flashlight sharp": Ionicons.flashlight_sharp,
  "checkmark circle": Ionicons.checkmark_circle,
  "file tray full sharp": Ionicons.file_tray_full_sharp,
  "magnet outline": Ionicons.magnet_outline,
  "reload circle sharp": Ionicons.reload_circle_sharp,
  "map outline": Ionicons.map_outline,
  "map": Ionicons.map,
  "chevron forward circle outline": Ionicons.chevron_forward_circle_outline,
  "barbell sharp": Ionicons.barbell_sharp,
  "cog": Ionicons.cog,
  "bag add sharp": Ionicons.bag_add_sharp,
  "filter circle outline": Ionicons.filter_circle_outline,
  "grid": Ionicons.grid,
  "paper plane outline": Ionicons.paper_plane_outline,
  "tv outline": Ionicons.tv_outline,
  "hardware chip outline": Ionicons.hardware_chip_outline,
  "journal outline": Ionicons.journal_outline

  /*"floor home 0 zero ground ": CommunityMaterialIcons.home_floor_0,
  "floor home 1 first ": CommunityMaterialIcons.home_floor_1,
  "floor home 2 second ": CommunityMaterialIcons.home_floor_2,
  "floor home 3 third ": CommunityMaterialIcons.home_floor_3,
  "floor home -1 negative one basement": CommunityMaterialIcons.home_floor_negative_1,
  "floor home a": CommunityMaterialIcons.home_floor_a,
  "floor home b": CommunityMaterialIcons.home_floor_b,
  "floor home g": CommunityMaterialIcons.home_floor_g,
  "floor home l": CommunityMaterialIcons.home_floor_l,*/
};
