name: Build Releases
on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "development"
    tags:
      # normal versions
      - "v[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: {}
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '21.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: 3.32.6
      - name: Check format
        run: dart format --set-exit-if-changed